name: Run tests
on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: TypeScript build
      run: yarn build
    - name: Run
      env:
        VITEST_NAMESPACE: VitestNotify

        TELEGRAM_KEY: ${{ secrets.TELEGRAM_KEY }}
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}

        SURGE_EMAIL: ${{ secrets.SURGE_EMAIL }}
        SURGE_PASSWORD: ${{ secrets.SURGE_PASSWORD }}
        SURGE_URL: ${{ secrets.SURGE_URL }}

        NOTION_KEY: ${{ secrets.NOTION_KEY }}
        NOTION_TESTS_DB: 41d1329f2d214f078484d3a089746cd9
        NOTION_ISSUES_DB: b73c2e4d536746d4bb94dd38b812d835
      run: yarn test
